#!/usr/bin/env bash
# This script displays "Best School" 10 times but at 9 iteration, adds a 'Hi' beneath
((i=0))
while ((i<10)); do
	echo "Best School"
	if ((i == 8))
	then
		echo "Hi"
	fi
	((i++))
done
