#!/usr/bin/env bash
# This script displays "Best School" 8 times, with 'bad luck' at 4th and 'good luck' at 8th
((i=0))
while ((i<10)); do
    if ((i == 3))
    then
        echo "bad luck"
    elif ((i == 7))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
