#!/usr/bin/env bash
# This script displays numbers 1 to 20; displays some texts after 4th, 9th and 17th iterations
((i=1))
while ((i<21)); do
    echo $i
    case $i in
        "4") echo "bad luck from China"
        ;;
        "9") echo "bad luck from Japan"
        ;;
        "17") echo "bad luck from Italy"
        ;;
    esac
    ((i++))
done
